export const defaultTheme = {
  'yellow-dark': '#a77b2a',
  'yellow-base': '#c9a96a',
  'yellow-light': '#f2e5cd',
  'green-dark': '#6f1f33',
  'green-base': '#9b4052',
  'purple-light': '#eee7e8',
  'base-title': '#7d263a',
  'base-subtitle': '#2b2827',
  'base-text': '#5a5552',
  'base-label': '#9a918d',
  'base-hover': '#f2ece9',
  'base-button': '#f0ebe8',
  'base-input': '#faf8f6',
  'base-card': '#ffffff',
  'base-background': '#f7f6f3',
  'base-white': '#ffffff',
  'base-nav': '#2b2827',
  'blue-home': '#f2ece8',
  'base-background-accordion': '#f4efec',
  'footer-color': '#641d30',
  'footer-blue-dark': '#4c1424',
  'header-color': '#ffffff',
  'menu-color': '#fbf8f6',
  'MENU-TEXT-HOVER': '#a77b2a',
}
